In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\Rudra\Desktop\credit-risk-ml\data\Raw\loan.csv", low_memory = False)

In [5]:
df

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599,5000,5000,4975.0,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.0,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.0,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.0,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39712,92187,92174,2500,2500,1075.0,36 months,8.07%,78.42,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39713,90665,90607,8500,8500,875.0,36 months,10.28%,275.38,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39714,90395,90390,5000,5000,1325.0,36 months,8.07%,156.84,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39715,90376,89243,5000,5000,650.0,36 months,7.43%,155.38,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39716,87023,86999,7500,7500,800.0,36 months,13.75%,255.43,E,E2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,3.971700e+04,3.971700e+04,39717.000000,39717.000000,39717.000000,39717.000000,3.971700e+04,39717.000000,39717.000000,39717.000000,...,0.0,0.0,0.0,0.0,39020.000000,39678.0,0.0,0.0,0.0,0.0
mean,6.831319e+05,8.504636e+05,11219.443815,10947.713196,10397.448868,324.561922,6.896893e+04,13.315130,0.146512,0.869200,...,NaN,NaN,NaN,NaN,0.043260,0.0,NaN,NaN,NaN,NaN
std,2.106941e+05,2.656783e+05,7456.670694,7187.238670,7128.450439,208.874874,6.379377e+04,6.678594,0.491812,1.070219,...,NaN,NaN,NaN,NaN,0.204324,0.0,NaN,NaN,NaN,NaN
min,5.473400e+04,7.069900e+04,500.000000,500.000000,0.000000,15.690000,4.000000e+03,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
25%,5.162210e+05,6.667800e+05,5500.000000,5400.000000,5000.000000,167.020000,4.040400e+04,8.170000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
50%,6.656650e+05,8.508120e+05,10000.000000,9600.000000,8975.000000,280.220000,5.900000e+04,13.400000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
75%,8.377550e+05,1.047339e+06,15000.000000,15000.000000,14400.000000,430.780000,8.230000e+04,18.600000,0.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN
max,1.077501e+06,1.314167e+06,35000.000000,35000.000000,35000.000000,1305.190000,6.000000e+06,29.990000,11.000000,8.000000,...,NaN,NaN,NaN,NaN,2.000000,0.0,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Columns: 111 entries, id to total_il_high_credit_limit
dtypes: float64(74), int64(13), object(24)
memory usage: 33.6+ MB

In [8]:
col = list(df.dtypes.items())

In [9]:
col

[('id', dtype('int64')),
 ('member_id', dtype('int64')),
 ('loan_amnt', dtype('int64')),
 ('funded_amnt', dtype('int64')),
 ('funded_amnt_inv', dtype('float64')),
 ('term', dtype('O')),
 ('int_rate', dtype('O')),
 ('installment', dtype('float64')),
 ('grade', dtype('O')),
 ('sub_grade', dtype('O')),
 ('emp_title', dtype('O')),
 ('emp_length', dtype('O')),
 ('home_ownership', dtype('O')),
 ('annual_inc', dtype('float64')),
 ('verification_status', dtype('O')),
 ('issue_d', dtype('O')),
 ('loan_status', dtype('O')),
 ('pymnt_plan', dtype('O')),
 ('url', dtype('O')),
 ('desc', dtype('O')),
 ('purpose', dtype('O')),
 ('title', dtype('O')),
 ('zip_code', dtype('O')),
 ('addr_state', dtype('O')),
 ('dti', dtype('float64')),
 ('delinq_2yrs', dtype('int64')),
 ('earliest_cr_line', dtype('O')),
 ('inq_last_6mths', dtype('int64')),
 ('mths_since_last_delinq', dtype('float64')),
 ('mths_since_last_record', dtype('float64')),
 ('open_acc', dtype('int64')),
 ('pub_rec', dtype('int64')),
 ('revol_bal', dtype('int64')),
 ('revol_util', dtype('O')),
 ('total_acc', dtype('int64')),
 ('initial_list_status', dtype('O')),
 ('out_prncp', dtype('float64')),
 ('out_prncp_inv', dtype('float64')),
 ('total_pymnt', dtype('float64')),
 ('total_pymnt_inv', dtype('float64')),
 ('total_rec_prncp', dtype('float64')),
 ('total_rec_int', dtype('float64')),
 ('total_rec_late_fee', dtype('float64')),
 ('recoveries', dtype('float64')),
 ('collection_recovery_fee', dtype('float64')),
 ('last_pymnt_d', dtype('O')),
 ('last_pymnt_amnt', dtype('float64')),
 ('next_pymnt_d', dtype('O')),
 ('last_credit_pull_d', dtype('O')),
 ('collections_12_mths_ex_med', dtype('float64')),
 ('mths_since_last_major_derog', dtype('float64')),
 ('policy_code', dtype('int64')),
 ('application_type', dtype('O')),
 ('annual_inc_joint', dtype('float64')),
 ('dti_joint', dtype('float64')),
 ('verification_status_joint', dtype('float64')),
 ('acc_now_delinq', dtype('int64')),
 ('tot_coll_amt', dtype('float64')),
 ('tot_cur_bal', dtype('float64')),
 ('open_acc_6m', dtype('float64')),
 ('open_il_6m', dtype('float64')),
 ('open_il_12m', dtype('float64')),
 ('open_il_24m', dtype('float64')),
 ('mths_since_rcnt_il', dtype('float64')),
 ('total_bal_il', dtype('float64')),
 ('il_util', dtype('float64')),
 ('open_rv_12m', dtype('float64')),
 ('open_rv_24m', dtype('float64')),
 ('max_bal_bc', dtype('float64')),
 ('all_util', dtype('float64')),
 ('total_rev_hi_lim', dtype('float64')),
 ('inq_fi', dtype('float64')),
 ('total_cu_tl', dtype('float64')),
 ('inq_last_12m', dtype('float64')),
 ('acc_open_past_24mths', dtype('float64')),
 ('avg_cur_bal', dtype('float64')),
 ('bc_open_to_buy', dtype('float64')),
 ('bc_util', dtype('float64')),
 ('chargeoff_within_12_mths', dtype('float64')),
 ('delinq_amnt', dtype('int64')),
 ('mo_sin_old_il_acct', dtype('float64')),
 ('mo_sin_old_rev_tl_op', dtype('float64')),
 ('mo_sin_rcnt_rev_tl_op', dtype('float64')),
 ('mo_sin_rcnt_tl', dtype('float64')),
 ('mort_acc', dtype('float64')),
 ('mths_since_recent_bc', dtype('float64')),
 ('mths_since_recent_bc_dlq', dtype('float64')),
 ('mths_since_recent_inq', dtype('float64')),
 ('mths_since_recent_revol_delinq', dtype('float64')),
 ('num_accts_ever_120_pd', dtype('float64')),
 ('num_actv_bc_tl', dtype('float64')),
 ('num_actv_rev_tl', dtype('float64')),
 ('num_bc_sats', dtype('float64')),
 ('num_bc_tl', dtype('float64')),
 ('num_il_tl', dtype('float64')),
 ('num_op_rev_tl', dtype('float64')),
 ('num_rev_accts', dtype('float64')),
 ('num_rev_tl_bal_gt_0', dtype('float64')),
 ('num_sats', dtype('float64')),
 ('num_tl_120dpd_2m', dtype('float64')),
 ('num_tl_30dpd', dtype('float64')),
 ('num_tl_90g_dpd_24m', dtype('float64')),
 ('num_tl_op_past_12m', dtype('float64')),
 ('pct_tl_nvr_dlq', dtype('float64')),
 ('percent_bc_gt_75', dtype('float64')),
 ('pub_rec_bankruptcies', dtype('float64')),
 ('tax_liens', dtype('float64')),
 ('tot_hi_cred_lim', dtype('float64')),
 ('total_bal_ex_mort', dtype('float64')),
 ('total_bc_limit', dtype('float64')),
 ('total_il_high_credit_limit', dtype('float64'))]

In [10]:
list(df['loan_status'])

['Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Current',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Current',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Current',
 'Current',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Current',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Current',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Charged Off',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Charged Off',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Current',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Current',
 'Current',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Charged Off',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 'Fully Paid',
 ...]

In [11]:
df['loan_status'].isnull().sum()

np.int64(0)

In [12]:
df['loan_amnt'].isnull().sum()

np.int64(0)

In [13]:
df['int_rate'].isnull().sum()

np.int64(0)

In [14]:
df['grade'].isnull().sum()

np.int64(0)

In [15]:
df['home_ownership'].isnull().sum()

np.int64(0)

In [16]:
df.isnull().sum().idxmax()

'mths_since_last_major_derog'

In [17]:
dict(df.isnull().sum().sort_values(ascending=False).head(111))

{'num_il_tl': np.int64(39717),
 'num_bc_sats': np.int64(39717),
 'num_bc_tl': np.int64(39717),
 'num_actv_bc_tl': np.int64(39717),
 'num_accts_ever_120_pd': np.int64(39717),
 'mths_since_recent_revol_delinq': np.int64(39717),
 'num_actv_rev_tl': np.int64(39717),
 'mths_since_recent_inq': np.int64(39717),
 'num_tl_90g_dpd_24m': np.int64(39717),
 'num_tl_30dpd': np.int64(39717),
 'num_tl_120dpd_2m': np.int64(39717),
 'num_sats': np.int64(39717),
 'num_rev_tl_bal_gt_0': np.int64(39717),
 'num_rev_accts': np.int64(39717),
 'pct_tl_nvr_dlq': np.int64(39717),
 'mo_sin_old_il_acct': np.int64(39717),
 'mo_sin_old_rev_tl_op': np.int64(39717),
 'mo_sin_rcnt_rev_tl_op': np.int64(39717),
 'mo_sin_rcnt_tl': np.int64(39717),
 'mths_since_recent_bc': np.int64(39717),
 'mort_acc': np.int64(39717),
 'mths_since_recent_bc_dlq': np.int64(39717),
 'bc_util': np.int64(39717),
 'total_rev_hi_lim': np.int64(39717),
 'all_util': np.int64(39717),
 'bc_open_to_buy': np.int64(39717),
 'avg_cur_bal': np.int64(39717),
 'acc_open_past_24mths': np.int64(39717),
 'inq_last_12m': np.int64(39717),
 'total_cu_tl': np.int64(39717),
 'inq_fi': np.int64(39717),
 'mths_since_rcnt_il': np.int64(39717),
 'total_bal_il': np.int64(39717),
 'il_util': np.int64(39717),
 'open_rv_12m': np.int64(39717),
 'open_rv_24m': np.int64(39717),
 'max_bal_bc': np.int64(39717),
 'open_il_6m': np.int64(39717),
 'open_il_24m': np.int64(39717),
 'verification_status_joint': np.int64(39717),
 'tot_coll_amt': np.int64(39717),
 'tot_cur_bal': np.int64(39717),
 'open_acc_6m': np.int64(39717),
 'open_il_12m': np.int64(39717),
 'annual_inc_joint': np.int64(39717),
 'dti_joint': np.int64(39717),
 'mths_since_last_major_derog': np.int64(39717),
 'total_bc_limit': np.int64(39717),
 'percent_bc_gt_75': np.int64(39717),
 'total_bal_ex_mort': np.int64(39717),
 'tot_hi_cred_lim': np.int64(39717),
 'total_il_high_credit_limit': np.int64(39717),
 'num_tl_op_past_12m': np.int64(39717),
 'num_op_rev_tl': np.int64(39717),
 'next_pymnt_d': np.int64(38577),
 'mths_since_last_record': np.int64(36931),
 'mths_since_last_delinq': np.int64(25682),
 'desc': np.int64(12942),
 'emp_title': np.int64(2459),
 'emp_length': np.int64(1075),
 'pub_rec_bankruptcies': np.int64(697),
 'last_pymnt_d': np.int64(71),
 'chargeoff_within_12_mths': np.int64(56),
 'collections_12_mths_ex_med': np.int64(56),
 'revol_util': np.int64(50),
 'tax_liens': np.int64(39),
 'title': np.int64(11),
 'last_credit_pull_d': np.int64(2),
 'total_rec_prncp': np.int64(0),
 'total_pymnt_inv': np.int64(0),
 'total_rec_int': np.int64(0),
 'last_pymnt_amnt': np.int64(0),
 'collection_recovery_fee': np.int64(0),
 'recoveries': np.int64(0),
 'total_rec_late_fee': np.int64(0),
 'sub_grade': np.int64(0),
 'home_ownership': np.int64(0),
 'annual_inc': np.int64(0),
 'verification_status': np.int64(0),
 'loan_amnt': np.int64(0),
 'member_id': np.int64(0),
 'funded_amnt_inv': np.int64(0),
 'funded_amnt': np.int64(0),
 'id': np.int64(0),
 'int_rate': np.int64(0),
 'term': np.int64(0),
 'total_pymnt': np.int64(0),
 'total_acc': np.int64(0),
 'out_prncp_inv': np.int64(0),
 'out_prncp': np.int64(0),
 'initial_list_status': np.int64(0),
 'pub_rec': np.int64(0),
 'revol_bal': np.int64(0),
 'inq_last_6mths': np.int64(0),
 'open_acc': np.int64(0),
 'loan_status': np.int64(0),
 'issue_d': np.int64(0),
 'delinq_2yrs': np.int64(0),
 'earliest_cr_line': np.int64(0),
 'dti': np.int64(0),
 'addr_state': np.int64(0),
 'purpose': np.int64(0),
 'zip_code': np.int64(0),
 'pymnt_plan': np.int64(0),
 'url': np.int64(0),
 'grade': np.int64(0),
 'installment': np.int64(0),
 'policy_code': np.int64(0),
 'application_type': np.int64(0),
 'acc_now_delinq': np.int64(0),
 'delinq_amnt': np.int64(0)}

In [18]:
df = df.drop(columns=['id', 'member_id', 'url','desc','title','out_prncp','out_prncp_inv','total_pymnt','total_pymnt_inv','total_rec_prncp','total_rec_int','total_rec_late_fee','recoveries','collection_recovery_fee','last_pymnt_d','last_pymnt_amnt','next_pymnt_d','last_credit_pull_d'])

In [19]:
df = df.drop(columns=['zip_code'])

In [20]:
df = df.drop(columns=['sub_grade'])

In [21]:
X = df.drop('loan_status', axis=1)
y = df['loan_status']

In [22]:
cat_cols = [
    'term',
    'home_ownership',
    'verification_status',
    'pymnt_plan',
    'purpose',
    'addr_state',
    'initial_list_status',
    'application_type'
]

In [23]:
X_encoded = pd.get_dummies(
    X,
    columns=cat_cols,
    drop_first=True
)

In [24]:
X_encoded.shape

(39717, 151)

In [25]:
grade_mapping = {
    'A': 1,
    'B': 2,
    'C': 3,
    'D': 4,
    'E': 5,
    'F': 6,
    'G': 7
}

In [26]:
X['grade'] = X['grade'].map(grade_mapping)

In [27]:
emp_length_mapping = {
    '< 1 year': 0,
    '1 year': 1,
    '2 years': 2,
    '3 years': 3,
    '4 years': 4,
    '5 years': 5,
    '6 years': 6,
    '7 years': 7,
    '8 years': 8,
    '9 years': 9,
    '10+ years': 10,
    'n/a': None
}

In [28]:
X['emp_length'] = X['emp_length'].map(emp_length_mapping)

In [29]:
X['grade'].unique()
#X['emp_length'].unique()

array([2, 3, 1, 5, 6, 4, 7])

In [30]:
X['earliest_cr_line'] = pd.to_datetime(
    X['earliest_cr_line'],
    format='%b-%y',
    errors='coerce'
)

X['issue_d'] = pd.to_datetime(
    X['issue_d'],
    format='%b-%y',
    errors='coerce'
)

In [31]:
X['issue_d'].head()
X['earliest_cr_line'].head()

0   1985-01-01
1   1999-04-01
2   2001-11-01
3   1996-02-01
4   1996-01-01
Name: earliest_cr_line, dtype: datetime64[ns]

In [32]:
X['credit_history_years'] = (
    X['issue_d'] - X['earliest_cr_line']
).dt.days / 365

In [33]:
X.drop(['earliest_cr_line', 'issue_d'], axis=1, inplace=True)

In [34]:
X['credit_history_years'].describe()

count    39717.000000
mean        13.573435
std          7.428207
min        -60.041096
25%          9.090411
50%         12.512329
75%         17.010959
max         42.780822
Name: credit_history_years, dtype: float64

In [35]:
X.isna().sum().sort_values(ascending=False).head(15)

bc_util                 39717
inq_fi                  39717
total_rev_hi_lim        39717
all_util                39717
bc_open_to_buy          39717
avg_cur_bal             39717
acc_open_past_24mths    39717
inq_last_12m            39717
total_cu_tl             39717
total_bal_il            39717
il_util                 39717
open_rv_12m             39717
open_rv_24m             39717
max_bal_bc              39717
mths_since_rcnt_il      39717
dtype: int64

In [36]:
X.drop(
    columns=[
        'annual_inc_joint',
        'dti_joint',
        'verification_status_joint'
    ],
    inplace=True,
    errors='ignore'
)

In [37]:
num_cols = X.select_dtypes(include=['int64', 'float64']).columns

X[num_cols] = X[num_cols].fillna(X[num_cols].median())

In [38]:
cat_cols = X.select_dtypes(include='object').columns
X[cat_cols] = X[cat_cols].fillna('Unknown')

In [39]:
X['credit_history_years'].isna().sum()

np.int64(0)

In [40]:
X.select_dtypes(include='object').columns

Index(['term', 'int_rate', 'emp_title', 'home_ownership',
       'verification_status', 'pymnt_plan', 'purpose', 'addr_state',
       'revol_util', 'initial_list_status', 'application_type'],
      dtype='object')

In [41]:
X.isna().sum().sum()

np.int64(2025567)

In [42]:
cols_with_many_nans = [
    'bc_util', 'inq_fi', 'total_rev_hi_lim', 'all_util',
    'bc_open_to_buy', 'avg_cur_bal', 'acc_open_past_24mths',
    'inq_last_12m', 'total_cu_tl', 'total_bal_il', 'il_util',
    'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
    'mths_since_rcnt_il'
]

X[cols_with_many_nans] = X[cols_with_many_nans].fillna(
    X[cols_with_many_nans].median()
)

In [43]:
X.isna().sum().sum()

np.int64(2025567)

In [44]:
missing = X.isna().sum()
missing = missing[missing > 0].sort_values(ascending=False)
missing

mths_since_last_major_derog       39717
tot_coll_amt                      39717
tot_cur_bal                       39717
open_acc_6m                       39717
open_il_6m                        39717
open_il_12m                       39717
open_il_24m                       39717
mths_since_rcnt_il                39717
total_bal_il                      39717
il_util                           39717
open_rv_12m                       39717
open_rv_24m                       39717
max_bal_bc                        39717
all_util                          39717
total_rev_hi_lim                  39717
inq_fi                            39717
total_cu_tl                       39717
inq_last_12m                      39717
acc_open_past_24mths              39717
avg_cur_bal                       39717
bc_open_to_buy                    39717
bc_util                           39717
mo_sin_old_il_acct                39717
mo_sin_old_rev_tl_op              39717
mo_sin_rcnt_rev_tl_op             39717
mo_sin_rcnt_tl                    39717
mort_acc                          39717
mths_since_recent_bc              39717
mths_since_recent_bc_dlq          39717
mths_since_recent_inq             39717
mths_since_recent_revol_delinq    39717
num_accts_ever_120_pd             39717
num_actv_bc_tl                    39717
num_actv_rev_tl                   39717
num_bc_sats                       39717
num_bc_tl                         39717
num_il_tl                         39717
num_op_rev_tl                     39717
num_rev_accts                     39717
num_rev_tl_bal_gt_0               39717
num_sats                          39717
num_tl_120dpd_2m                  39717
num_tl_30dpd                      39717
num_tl_90g_dpd_24m                39717
num_tl_op_past_12m                39717
pct_tl_nvr_dlq                    39717
percent_bc_gt_75                  39717
tot_hi_cred_lim                   39717
total_bal_ex_mort                 39717
total_bc_limit                    39717
total_il_high_credit_limit        39717
dtype: int64

In [45]:
months_cols = [
    col for col in X.columns
    if col.startswith('mths_') or col.startswith('mo_sin_')
]

X[months_cols] = X[months_cols].fillna(0)

In [46]:
count_cols = [
    'num_accts_ever_120_pd','num_actv_bc_tl','num_actv_rev_tl',
    'num_bc_sats','num_bc_tl','num_il_tl','num_op_rev_tl',
    'num_rev_accts','num_rev_tl_bal_gt_0','num_sats',
    'num_tl_120dpd_2m','num_tl_30dpd','num_tl_90g_dpd_24m',
    'num_tl_op_past_12m','open_acc_6m','open_il_6m',
    'open_il_12m','open_il_24m','open_rv_12m','open_rv_24m',
    'inq_fi','inq_last_12m','acc_open_past_24mths','total_cu_tl'
]

X[count_cols] = X[count_cols].fillna(0)

In [47]:
continuous_cols = [
    'tot_coll_amt','tot_cur_bal','total_bal_il','il_util',
    'max_bal_bc','all_util','total_rev_hi_lim','avg_cur_bal',
    'bc_open_to_buy','bc_util','tot_hi_cred_lim',
    'total_bal_ex_mort','total_bc_limit',
    'total_il_high_credit_limit','percent_bc_gt_75',
    'pct_tl_nvr_dlq','mort_acc'
]

X[continuous_cols] = X[continuous_cols].fillna(
    X[continuous_cols].median()
)

In [48]:
X.isna().sum().sum()

np.int64(675189)

In [49]:
remaining = X.isna().sum()
remaining = remaining[remaining > 0].sort_values(ascending=False)
remaining

tot_coll_amt                  39717
tot_cur_bal                   39717
total_bal_il                  39717
il_util                       39717
max_bal_bc                    39717
all_util                      39717
total_rev_hi_lim              39717
avg_cur_bal                   39717
bc_open_to_buy                39717
bc_util                       39717
mort_acc                      39717
pct_tl_nvr_dlq                39717
percent_bc_gt_75              39717
tot_hi_cred_lim               39717
total_bal_ex_mort             39717
total_bc_limit                39717
total_il_high_credit_limit    39717
dtype: int64

In [50]:
final_continuous_cols = [
    'tot_coll_amt','tot_cur_bal','total_bal_il','il_util',
    'max_bal_bc','all_util','total_rev_hi_lim','avg_cur_bal',
    'bc_open_to_buy','bc_util','mort_acc','pct_tl_nvr_dlq',
    'percent_bc_gt_75','tot_hi_cred_lim','total_bal_ex_mort',
    'total_bc_limit','total_il_high_credit_limit'
]

X[final_continuous_cols] = X[final_continuous_cols].fillna(
    X[final_continuous_cols].median()
)

In [51]:
X.isna().sum().sum()

np.int64(675189)

In [52]:
X[[
    'tot_coll_amt','tot_cur_bal','total_bal_il','il_util',
    'max_bal_bc','all_util','total_rev_hi_lim','avg_cur_bal',
    'bc_open_to_buy','bc_util','mort_acc','pct_tl_nvr_dlq',
    'percent_bc_gt_75','tot_hi_cred_lim','total_bal_ex_mort',
    'total_bc_limit','total_il_high_credit_limit'
]].dtypes

tot_coll_amt                  float64
tot_cur_bal                   float64
total_bal_il                  float64
il_util                       float64
max_bal_bc                    float64
all_util                      float64
total_rev_hi_lim              float64
avg_cur_bal                   float64
bc_open_to_buy                float64
bc_util                       float64
mort_acc                      float64
pct_tl_nvr_dlq                float64
percent_bc_gt_75              float64
tot_hi_cred_lim               float64
total_bal_ex_mort             float64
total_bc_limit                float64
total_il_high_credit_limit    float64
dtype: object

In [53]:
X[[
    'tot_coll_amt','tot_cur_bal','total_bal_il','il_util',
    'max_bal_bc','all_util','total_rev_hi_lim','avg_cur_bal',
    'bc_open_to_buy','bc_util','mort_acc','pct_tl_nvr_dlq',
    'percent_bc_gt_75','tot_hi_cred_lim','total_bal_ex_mort',
    'total_bc_limit','total_il_high_credit_limit'
]].isna().all()

tot_coll_amt                  True
tot_cur_bal                   True
total_bal_il                  True
il_util                       True
max_bal_bc                    True
all_util                      True
total_rev_hi_lim              True
avg_cur_bal                   True
bc_open_to_buy                True
bc_util                       True
mort_acc                      True
pct_tl_nvr_dlq                True
percent_bc_gt_75              True
tot_hi_cred_lim               True
total_bal_ex_mort             True
total_bc_limit                True
total_il_high_credit_limit    True
dtype: bool

In [54]:
fully_empty_cols = [
    'tot_coll_amt','tot_cur_bal','total_bal_il','il_util',
    'max_bal_bc','all_util','total_rev_hi_lim','avg_cur_bal',
    'bc_open_to_buy','bc_util','mort_acc','pct_tl_nvr_dlq',
    'percent_bc_gt_75','tot_hi_cred_lim','total_bal_ex_mort',
    'total_bc_limit','total_il_high_credit_limit'
]

X.drop(columns=fully_empty_cols, inplace=True)

In [55]:
X.isna().sum().sum()

np.int64(0)

In [56]:
X.isnull().sum()

loan_amnt               0
funded_amnt             0
funded_amnt_inv         0
term                    0
int_rate                0
                       ..
num_tl_90g_dpd_24m      0
num_tl_op_past_12m      0
pub_rec_bankruptcies    0
tax_liens               0
credit_history_years    0
Length: 69, dtype: int64

In [58]:
df = df[df['loan_status'].isin(['Fully Paid', 'Charged Off'])]

df['target'] = df['loan_status'].map({
    'Fully Paid': 0,
    'Charged Off': 1
})

C:\Users\Rudra\AppData\Local\Temp\ipykernel_14192\1758216190.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'] = df['loan_status'].map({

In [59]:
df['target'].value_counts()
df['target'].dtype

dtype('int64')

In [61]:
list(df.dtypes)

[dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('O'),
 dtype('O'),
 dtype('float64'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('float64'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('float64'),
 dtype('int64'),
 dtype('O'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('int64'),
 dtype('O'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('O'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64')]

In [62]:
object_cols = df.select_dtypes(include='object').columns
object_cols

Index(['term', 'int_rate', 'grade', 'emp_title', 'emp_length',
       'home_ownership', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'purpose', 'addr_state', 'earliest_cr_line', 'revol_util',
       'initial_list_status', 'application_type'],
      dtype='object')

In [63]:
drop_cols = [
    'emp_title',
    'issue_d',
    'loan_status',
    'earliest_cr_line'
]

df = df.drop(columns=drop_cols)

In [64]:
df['term'] = df['term'].str.extract('(\d+)').astype(int)

In [65]:
df['revol_util'] = df['revol_util'].str.replace('%','').astype(float)

In [66]:
grade_map = {'A':1,'B':2,'C':3,'D':4,'E':5,'F':6,'G':7}
df['grade'] = df['grade'].map(grade_map)

In [67]:
emp_map = {
    '< 1 year':0, '1 year':1, '2 years':2, '3 years':3, '4 years':4,
    '5 years':5, '6 years':6, '7 years':7, '8 years':8, '9 years':9,
    '10+ years':10
}
df['emp_length'] = df['emp_length'].map(emp_map)

In [68]:
df = pd.get_dummies(
    df,
    columns=[
        'home_ownership',
        'verification_status',
        'pymnt_plan',
        'purpose',
        'addr_state',
        'initial_list_status',
        'application_type'
    ],
    drop_first=True
)

In [69]:
df.dtypes.unique()

array([dtype('int64'), dtype('float64'), dtype('O'), dtype('bool')],
      dtype=object)

In [70]:
df.select_dtypes(include='object').columns

Index(['int_rate'], dtype='object')

In [71]:
df['int_rate'] = (
    df['int_rate']
    .astype(str)
    .str.replace('%', '', regex=False)
    .astype(float)
)

In [72]:
df.dtypes.unique()

array([dtype('int64'), dtype('float64'), dtype('bool')], dtype=object)

In [73]:
df.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,annual_inc,dti,...,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,target
count,38577.000000,38577.000000,38577.000000,38577.000000,38577.000000,38577.000000,38577.000000,37544.000000,3.857700e+04,38577.000000,...,0.0,0.0,0.0,37880.000000,38538.0,0.0,0.0,0.0,0.0,38577.000000
mean,11047.025430,10784.058506,10222.481123,41.898437,11.932219,322.466318,2.553361,4.940976,6.877797e+04,13.272727,...,NaN,NaN,NaN,0.043479,0.0,NaN,NaN,NaN,NaN,0.145864
std,7348.441646,7090.306027,7022.720644,10.333136,3.691327,208.639215,1.380003,3.557082,6.421868e+04,6.673044,...,NaN,NaN,NaN,0.204583,0.0,NaN,NaN,NaN,NaN,0.352975
min,500.000000,500.000000,0.000000,36.000000,5.420000,15.690000,1.000000,0.000000,4.000000e+03,0.000000,...,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN,0.000000
25%,5300.000000,5200.000000,5000.000000,36.000000,8.940000,165.740000,1.000000,2.000000,4.000000e+04,8.130000,...,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN,0.000000
50%,9600.000000,9550.000000,8733.440000,36.000000,11.710000,277.860000,2.000000,4.000000,5.886800e+04,13.370000,...,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN,0.000000
75%,15000.000000,15000.000000,14000.000000,36.000000,14.380000,425.550000,3.000000,9.000000,8.200000e+04,18.560000,...,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,NaN,0.000000
max,35000.000000,35000.000000,35000.000000,60.000000,24.400000,1305.190000,7.000000,10.000000,6.000000e+06,29.990000,...,NaN,NaN,NaN,2.000000,0.0,NaN,NaN,NaN,NaN,1.000000

In [74]:
df = df.dropna(axis=1, how='all')

In [75]:
df.shape

(38577, 95)

In [76]:
X = df.drop('target', axis=1)
y = df['target']

In [77]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [78]:
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

In [79]:
X_scaled.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,annual_inc,dti,...,addr_state_SD,addr_state_TN,addr_state_TX,addr_state_UT,addr_state_VA,addr_state_VT,addr_state_WA,addr_state_WI,addr_state_WV,addr_state_WY
count,3.857700e+04,3.857700e+04,3.857700e+04,3.857700e+04,3.857700e+04,3.857700e+04,3.857700e+04,3.754400e+04,3.857700e+04,3.857700e+04,...,3.857700e+04,38577.000000,3.857700e+04,3.857700e+04,3.857700e+04,3.857700e+04,3.857700e+04,3.857700e+04,3.857700e+04,3.857700e+04
mean,6.483424e-17,2.357609e-17,8.251630e-17,-1.886087e-16,-2.416549e-16,7.662228e-17,-1.473505e-17,1.090115e-16,-2.910173e-17,8.841033e-17,...,-1.068291e-17,0.000000,3.683764e-17,-2.210258e-17,-3.241712e-17,-1.252480e-17,2.247096e-17,5.433551e-18,2.099745e-17,1.141967e-17
std,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,...,1.000013e+00,1.000013,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00,1.000013e+00
min,-1.435292e+00,-1.450458e+00,-1.455649e+00,-5.708348e-01,-1.764217e+00,-1.470387e+00,-1.125636e+00,-1.389072e+00,-1.008722e+00,-1.989032e+00,...,-4.012184e-02,-0.020997,-2.720841e-01,-8.108849e-02,-1.918154e-01,-3.709132e-02,-1.471860e-01,-1.074121e-01,-6.692222e-02,-4.558601e-02
25%,-7.820842e-01,-7.875726e-01,-7.436646e-01,-5.708348e-01,-8.106183e-01,-7.511932e-01,-1.125636e+00,-8.268056e-01,-4.481304e-01,-7.706818e-01,...,-4.012184e-02,-0.020997,-2.720841e-01,-8.108849e-02,-1.918154e-01,-3.709132e-02,-1.471860e-01,-1.074121e-01,-6.692222e-02,-4.558601e-02
50%,-1.969185e-01,-1.740510e-01,-2.120347e-01,-5.708348e-01,-6.020099e-02,-2.137992e-01,-4.009905e-01,-2.645395e-01,-1.543181e-01,1.457719e-02,...,-4.012184e-02,-0.020997,-2.720841e-01,-8.108849e-02,-1.918154e-01,-3.709132e-02,-1.471860e-01,-1.074121e-01,-6.692222e-02,-4.558601e-02
75%,5.379407e-01,5.946141e-01,5.379066e-01,-5.708348e-01,6.631254e-01,4.940827e-01,3.236552e-01,1.141126e+00,2.058933e-01,7.923432e-01,...,-4.012184e-02,-0.020997,-2.720841e-01,-8.108849e-02,-1.918154e-01,-3.709132e-02,-1.471860e-01,-1.074121e-01,-6.692222e-02,-4.558601e-02
max,3.259641e+00,3.415403e+00,3.528239e+00,1.751820e+00,3.377631e+00,4.710219e+00,3.222238e+00,1.422259e+00,9.236096e+01,2.505227e+00,...,2.492408e+01,47.625994,3.675335e+00,1.233221e+01,5.213345e+00,2.696049e+01,6.794126e+00,9.309941e+00,1.494272e+01,2.193656e+01

In [81]:
X_scaled.isnull().sum().sum()

np.int64(62673)

In [82]:
na_counts = X.isnull().sum()
na_counts[na_counts > 0].sort_values(ascending=False)

mths_since_last_record        35837
mths_since_last_delinq        24905
emp_length                     1033
pub_rec_bankruptcies            697
chargeoff_within_12_mths         56
collections_12_mths_ex_med       56
revol_util                       50
tax_liens                        39
dtype: int64

In [83]:
X = X.drop(columns=[
    'mths_since_last_record',
    'mths_since_last_delinq'
])

In [84]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')
X_imputed = imputer.fit_transform(X)
X_imputed = pd.DataFrame(X_imputed, columns=X.columns)

In [85]:
X_imputed.isnull().sum().sum()

np.int64(0)

In [86]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

In [87]:
X_scaled.isnull().sum().sum()

np.int64(0)

In [88]:
X_scaled.mean().abs().mean()

np.float64(3.0970641581999387e-17)

In [89]:
X_scaled.std().mean()

np.float64(0.9347947247334827)

In [90]:
df.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,annual_inc,dti,...,revol_util,total_acc,collections_12_mths_ex_med,policy_code,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens,target
count,38577.000000,38577.000000,38577.000000,38577.000000,38577.000000,38577.000000,38577.000000,37544.000000,3.857700e+04,38577.000000,...,38527.000000,38577.000000,38521.0,38577.0,38577.0,38521.0,38577.0,37880.000000,38538.0,38577.000000
mean,11047.025430,10784.058506,10222.481123,41.898437,11.932219,322.466318,2.553361,4.940976,6.877797e+04,13.272727,...,48.702777,22.052648,0.0,1.0,0.0,0.0,0.0,0.043479,0.0,0.145864
std,7348.441646,7090.306027,7022.720644,10.333136,3.691327,208.639215,1.380003,3.557082,6.421868e+04,6.673044,...,28.364741,11.425861,0.0,0.0,0.0,0.0,0.0,0.204583,0.0,0.352975
min,500.000000,500.000000,0.000000,36.000000,5.420000,15.690000,1.000000,0.000000,4.000000e+03,0.000000,...,0.000000,2.000000,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000
25%,5300.000000,5200.000000,5000.000000,36.000000,8.940000,165.740000,1.000000,2.000000,4.000000e+04,8.130000,...,25.200000,13.000000,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000
50%,9600.000000,9550.000000,8733.440000,36.000000,11.710000,277.860000,2.000000,4.000000,5.886800e+04,13.370000,...,49.100000,20.000000,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000
75%,15000.000000,15000.000000,14000.000000,36.000000,14.380000,425.550000,3.000000,9.000000,8.200000e+04,18.560000,...,72.300000,29.000000,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000
max,35000.000000,35000.000000,35000.000000,60.000000,24.400000,1305.190000,7.000000,10.000000,6.000000e+06,29.990000,...,99.900000,90.000000,0.0,1.0,0.0,0.0,0.0,2.000000,0.0,1.000000

In [91]:
constant_cols = [
    'policy_code',
    'collections_12_mths_ex_med',
    'chargeoff_within_12_mths',
    'acc_now_delinq',
    'delinq_amnt',
    'tax_liens'
]

df = df.drop(columns=constant_cols)

In [92]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

In [94]:
import os

os.makedirs("data/processed", exist_ok=True)

df.to_csv(
    "data/processed/credit_risk_processed.csv",
    index=False
)

In [95]:
X_scaled.to_csv(
    "data/processed/X_scaled.csv",
    index=False
)

In [96]:
y.to_csv(
    "data/processed/y.csv",
    index=False
)

In [97]:
import joblib

os.makedirs("models", exist_ok=True)

joblib.dump(imputer, "models/imputer.joblib")
joblib.dump(scaler, "models/scaler.joblib")

['models/scaler.joblib']

In [98]:
import os
print(os.getcwd())

C:\Users\Rudra\Desktop\credit-risk-ml\notebooks

In [99]:
df.to_csv("../data/processed/credit_risk_processed.csv", index=False)
X_scaled.to_csv("../data/processed/X_scaled.csv", index=False)
y.to_csv("../data/processed/y.csv", index=False)

In [100]:
df.to_csv(
    r"C:\Users\Rudra\Desktop\credit-risk-ml\data\processed\credit_risk_processed.csv",
    index=False
)

In [101]:
import joblib

os.makedirs("models", exist_ok=True)

joblib.dump(imputer, "../models/imputer.joblib")
joblib.dump(scaler, "../models/scaler.joblib")

['../models/scaler.joblib']